menu:
  Home: /
  Archives: /archives

addthis:
  enable: true
  pubid:
  facebook: true
  twitter: true
  google: true
  pinterest: true

facebook:
google_plus: true
twitter:
github: true

fancybox: true
google_analytics: true
rss: true