menu:
  Home: /
  Archives: /archives
  GitHub: http://github.com/lbkmono

addthis:
  enable: true
  pubid:
  facebook: true
  twitter: true
  google: true
  pinterest: true

facebook:
google_plus: true
twitter:
github: true

fancybox: true
google_analytics: UA-63312724-1
rss: /feed.xml